### ISSUE TITLE
Wrong INSTALL_RPATH on ROS

### ISSUE THREAD

**Issue by nim65s** [stack-of-tasks/eigenpy#353]
Hi,

Following https://github.com/jrl-umi3218/jrl-cmakemodules/pull/587 and associated issues, I guessed this hardcoded `INSTALL_RPATH` is also wrong:

https://github.com/stack-of-tasks/eigenpy/blob/f35c1e32b8e27481f8a9661a59305885756af3a9/python/CMakeLists.txt#L47

And it's true:

```
# LD_LIBRARY_PATH="" PYTHONPATH="/opt/ros/noetic/lib/python3/dist-packages/" python -c "import eigenpy"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/ros/noetic/lib/python3/dist-packages/eigenpy/__init__.py", line 5, in <module>
    from .eigenpy_pywrap import *  # noqa
ImportError: libeigenpy.so: cannot open shared object file: No such file or directory
# LD_LIBRARY_PATH="" PYTHONPATH="/opt/ros/noetic/lib/python3/dist-packages/" ldd /opt/ros/noetic/lib/python3/dist-packages/eigenpy/eigenpy_pywrap.cpython-38-x86_64-linux-gnu.so
	linux-vdso.so.1 (0x00007ffcddcfb000)
	libeigenpy.so => not found
	libboost_python38.so.1.71.0 => /lib/x86_64-linux-gnu/libboost_python38.so.1.71.0 (0x00007f9440af7000)
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f9440915000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f94408fa000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f9440708000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f94406e5000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f9440594000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f9440b83000)
# LD_LIBRARY_PATH="" PYTHONPATH="/opt/ros/noetic/lib/python3/dist-packages/" objdump -x /opt/ros/noetic/lib/python3/dist-packages/eigenpy/eigenpy_pywrap.cpython-38-x86_64-linux-gnu.so | grep PATH
  RUNPATH              $ORIGIN/../../..
  ```

I'll also fix this one. Even if ROS tooling correctly sets `LD_LIBRARY_PATH` to the `$ROS_PREFIX/lib/x86_64-linux-gnu` and workaround the issue, this looks fragile.

**Comment by jcarpent** [comment]
@nim65s I've merged #354 which contains your fix.
Thanks a lot for the nice fix.

Justin
